importjava.awt.event.ActionEvent;
importjava.awt.event.ActionListener;
importjavax.swing.JFrame;
importjavax.swing.*;
publicclassresgiterextendsJFrameimplementsActionListener
{
JLabell1=newJLabel("NAME");
JLabell2=newJLabel("PASSWORD");
JLabell3=newJLabel("SELECTCOUNTRY");
JLabell4=newJLabel("GENDER");
JTextFieldt1=newJTextField();
JCheckBoxc1=newJCheckBox("MALE");
JCheckBoxc2=newJCheckBox("FEMALE");
ButtonGroupbg=newButtonGroup();
JComboBoxc=newJComboBox();
JButtonb=newJButton("SUBMIT");
JPasswordFieldp=newJPasswordField();
publicresgiter()
{
this.setLayout(null);
this.setVisible(true);
this.setSize(700,600);
l1.setBounds(100,100,200,40);
l2.setBounds(100,200,200,40);
l3.setBounds(100,300,200,40);
l4.setBounds(100,400,200,40);
add(l1);
add(l2);
add(l3);
add(l4);
t1.setBounds(250,100,150,40);
add(t1);
p.setBounds(250,200,150,40);
add(p);
c1.setBounds(250,400,100,40);
c2.setBounds(350,400,100,40);
add(c1);
add(c2);
bg.add(c1);
bg.add(c2);
c.setBounds(250,300,120,30);
c.addItem("INDIA");
c.addItem("AMERICA");
c.addItem("AUSTRALIA");
c.addItem("PHILLIPHINES");
c.addItem("SPAIN");
add(c);
b.setBounds(200,540,100,60);
add(b);
b.addActionListener(this);
}
publicstaticvoidmain(String[]args)
{
newresgiter();
}
publicvoidactionPerformed(ActionEventar)
{
if(ar.getSource()==b)
{
this.hide();
Stringaa=t1.getText();
//newsubmit_op(aa);
}
}
}